FROM prestashop/prestashop:1.7.8

RUN apt-get update && apt-get install -y openssl

RUN mkdir -p /etc/apache2/private && mkdir -p /etc/apache2/certs

RUN openssl req -x509 -newkey rsa:4096 \
    -keyout /etc/apache2/private/localhost.key \
    -out /etc/apache2/certs/localhost.crt \
    -sha256 -days 3650 -nodes \
    -subj "/C=PL/ST=pomorskie/L=Gdansk/O=./OU=./CN=localhost" \
    -addext "basicConstraints=CA:FALSE"
